import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    // ▼▼ 新しいアプリを作るたびに、ここの 'アプリ名' を書き換えてください ▼▼
    template: '%s | アプリ名',
    default: 'アプリ名', // ← タイトル設定がないページで表示される名前
  },
  description: "Generated by create next app", // ← ここもアプリの説明文に変える
  // Google Search Consoleの所有権確認コードを入れる場所を確保
  verification: {
    google: "ここに確認コードを入れる",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
